language: node_js
node_js: '10'

jobs:
  include:
    - stage: Lint
      script: yarn lint
    - stage: Flow check
      script: yarn flow
    - stage: Release
      if: branch = master
      script:
        - yarn build
        - npx semantic-release
